name: Deploy
on:
  push:
    branches-ignore:
    - gh-pages
  pull_request:
    branches-ignore:
    - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Install & build
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
    - name: Deploy main
      uses: JamesIves/github-pages-deploy-action@3.7.1
      if: ${{ steps.extract_branch.outputs.branch == 'main' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
    - name: Deploy branch
      uses: JamesIves/github-pages-deploy-action@3.7.1
      if: ${{ steps.extract_branch.outputs.branch != 'main' }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        TARGET_FOLDER: staging/${{ steps.extract_branch.outputs.branch }}
        CLEAN: true
