name: Un-deploy from gh-pages
on:
  delete:
    branches-ignore:
    - main
    - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Undeploy gh-page
      run: |
        git fetch
        git checkout gh-pages
        if [ -d "staging/${{ steps.extract_branch.outputs.branch }}" ]; then
          git rm -r staging/${{ steps.extract_branch.outputs.branch }}
          git commit -m "Auto undeploy ${{ steps.extract_branch.outputs.branch }}"
          git push
        else
          echo "Nothing to un-deploy"
        fi
