name: Un-deploy from gh-pages
on:
  delete:
    branches-ignore:
    - main
    - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Extract branch name
      shell: bash
      run: REF="${{ github.event.ref }}" && echo "##[set-output name=branch;]$(echo ${REF#refs/heads/})"
      id: extract_branch
    - name: Undeploy gh-page
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        if [ -d "staging/${{ steps.extract_branch.outputs.branch }}" ]; then
          rm -r staging/${{ steps.extract_branch.outputs.branch }}
          git add --all .
          git commit -m "Auto undeploy ${{ steps.extract_branch.outputs.branch }}"
          git push
        else
          echo "Nothing to un-deploy"
        fi
